bin: [
  "core/_build/main.native" { "neal" }
]
lib: [
  "providers/kotlin/_build/kotlin.provider.cmxs" { "providers/kotlin.provider.cmxs" }
  "providers/swift/_build/swift.provider.cmxs" { "providers/swift.provider.cmxs" }
  "providers/python/_build/python.provider.cmxs" { "providers/python.provider.cmxs" }

  "reporters/cli/_build/cli.cmxs" { "reporters/cli/cli.reporter.cmxs" }
  "reporters/compact/_build/compact.cmxs" { "reporters/compact/compact.reporter.cmxs" }
]
